SWATParameters2<- tibble("OV_N.hru|change = absval" = c(0.01, 0.3),
                        "SOL_K.sol | change = relchg" =c(-0.5,0.5),
                        "CN2.mgt|change = relchg" = c(-0.5, 0.5),
                        "SOL_AWC.sol|change = relchg" = c(-0.5, 0.5),
                        "SURLAG.bsn|change = relchg" = c(-0.3, 0.3),
                        "ESCO.hru|change = relchg" = c(-0.5, 0.5),
                        "ALPHA_BF.gw|change = absval" = c(0, 1),
                        "CH_K2.rte|change = absval" = c(0, 500),
                        "CH_K1.sub|change = absval" = c(0, 300),
                        "CANMX.hru|change = absval" = c(0, 100),
                        "CH_N2.rte|change = absval" = c(0.01, 0.3),
                        "CH_N1.sub|change = absval" = c(0.01, 30),
                        "GW_REVAP.gw|change = absval" = c(0, 0.3),
                        "RCHRG_DP.gw|change = absval" = c(0, 1),
                        "EPCO.hru|change = relchg" = c(-0.5, 0.5),
                        "SHALLST.gw|change=absval"=c(0,50000),
                        "DEEPST.gw|change=absval"=c(0,50000),
                        "GW_DELAY.gw|change=absval"=c(0,500),
                        "GWHT.gw|change=absval"=c(0,25),
                        "GW_SPYLD.gw|change=absval"=c(0,0.4),
                        "GWQMN.gw|change=absval"=c(0,5000),
                        "REVAPMN.gw|change=absval"=c(0,500),
                        "SOL_Z.sol|change=relchg"=c(-0.5,0.5),
                        "LAT_TIME.hru|change=relchg"=c(-0.5,0.5))


SWATParameters<- tibble("GW_DELAY.gw|change = absval" = c(30, 450),
                        "OV_N.hru|change = absval" = c(0.01, 30),
                        "CN2.mgt|change = relchg" = c(-0.2, 0.2),
                        "REVAPMN.gw|change = absval" = c(0, 500),
                        "SOL_AWC.sol|change = absval" = c(0.01, 0.5),
                        "SURLAG.bsn|change = absval" = c(0, 24),
                        "ESCO.hru|change = absval" = c(0, 1),
                        "SHALLST.gw|change = absval" = c(0, 1000),
                        "GWQMN.gw|change = absval" = c(0, 5000),
                        "ALPHA_BF.gw|change = absval" = c(0, 1),
                        #"LAT_TIME.hru|change = absval" = c(0, 180),
                        "SLSOIL.hru|change = absval" = c(0, 150),
                        "HRU_SLP.hru|change = absval" = c(0, 0.6),
                        "CH_K2.rte|change = absval" = c(0, 500),
                        "SOL_Z.sol|change = abschg" = c(0, 1000),
                        "CH_K1.sub|change = absval" = c(0, 300),
                        "SLSUBBSN.hru|change = absval" = c(10, 150),
                        "CANMX.hru|change = absval" = c(0, 100),
                        "CH_N2.rte|change = absval" = c(0, 0.3),
                        "CH_N1.sub|change = absval" = c(0.01, 30),
                        "EVRCH.bsn|change = absval" = c(0.5, 1),
                        "GW_REVAP.gw|change = absval" = c(0, 0.3),
                        "RCHRG_DP.gw|change = absval" = c(0, 1),
                        "EPCO.hru|change = absval" = c(0, 1),
                        "PLAPS.sub|change = absval" = c(0, 100))



SWATParameters_f<- tibble("CN2.mgt|change = relchg" = c(-0.5, 0.5),
                          "CN2.hru| change = abschg" = c(-15, 10),
                        "SOL_AWC.sol|change = relchg" = c(-0.5, 0.5),
                        "RCHRG_DP.gw|change = absval" = c(0, 1),
                        "ESCO.hru|change = relchg" = c(-0.5, 0.5),
                        "ALPHA_BF.gw|change = absval" = c(0, 1),
                        'PERCO.hru | change = abschg' = c(-0.5, 0.5),
                        "CANMX.hru|change = absval" = c(0, 100),
                        "GW_REVAP.gw|change = absval" = c(0, 0.3),
                        'EPCO.hru | change = absval' = c(0, 1),
                        "SHALLST.gw|change=absval"=c(0,50000),
                        "DEEPST.gw|change=absval"=c(0,50000),
                        "GW_DELAY.gw|change=absval"=c(0,500),
                        "GW_SPYLD.gw|change=absval"=c(0,0.4),
                        "GWQMN.gw|change=absval"=c(0,5000)
                        )
